AWS_PROFILE_NAME = ''
AWS_ACCESS_KEY_ID = ''
AWS_SECRET_ACCESS_KEY = ''
ALERT_TOPIC_ARN = ''

INFURA_ACCOUNT = ''
LOCAL_ETH_NODE = 'http://127.0.0.1:8545'

OSM_NEXT_ALERT_THRESHOLD = 0
YEARN_3POOL_WITHDRAW_THRESHOLD = 0
